contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mysecondpipeline channel"
    url: https://nfcore.slack.com/channels/mysecondpipeline
    about: Discussion about the nf-core/mysecondpipeline pipeline
